builder:
  track: dev

labels:
  app: nginx-sidecar
  team: estafette-team
  language: docker

pipelines:
  set-pending-build-status:
    image: extensions/github-status:dev
    status: pending
    when:
      server == 'estafette'

  bake:
    image: docker:17.06.1-ce
    commands:
    - cp Dockerfile ./publish
    - cp /etc/ssl/certs/ca-certificates.crt ./publish
    - docker build -t estafette/${ESTAFETTE_LABEL_APP}:${ESTAFETTE_GIT_BRANCH} ./publish

  push-to-docker-hub:
    image: docker:17.06.1-ce
    env:
      DOCKER_HUB_USERNAME: estafette.secret(D8gy3KO6Fil7FaKs.KHLH6NCrIPtk6ObXaC_Y7i4xE2OY6QiorA==)
      DOCKER_HUB_PASSWORD: estafette.secret(ZpEKNFi_HPbvD_9g.Ugs4lPe9GgXgTKkfmSaE6A7yotFfxRilGRMV3DIEox2UmqdK)
    commands:
    - docker login --username=${DOCKER_HUB_USERNAME} --password="${DOCKER_HUB_PASSWORD}"
    - docker push estafette/${ESTAFETTE_LABEL_APP}:${ESTAFETTE_GIT_BRANCH}
    when:
      status == 'succeeded' &&
      branch == 'master' &&
      server == 'gocd'

  set-build-status:
    image: extensions/github-status:dev
    when:
      server == 'estafette'

  slack-notify:
    image: extensions/slack-build-status:dev
    webhook: estafette.secret(49oDHA1GU2Y9uNr9.1_rY9ehRjYRsHnVoW-_CcP70z2EvWYgcb3U7BteamAQgx6iXo_Zrgcf_ESs4AgvhA_o20FPllOoX6GoZ4VvZqepcS5KaOIi032ljAPDSO8-7xveayDxl63XGqp2c)
    name: ${ESTAFETTE_LABEL_APP}
    channels:
    - '#build-status'
    when:
      status == 'failed'